---
- name: Jenkins K8s | Préparer les manifests
  import_tasks: prepare.yml

- name: Jenkins K8s | Déployer Jenkins
  import_tasks: deploy.yml

- name: Jenkins K8s | Vérifier Jenkins
  import_tasks: verify.yml
