- name: Créer le dossier de certificats Docker pour Nexus
  file:
    path: "/etc/docker/certs.d/{{ nexus_registry_url }}"
    state: directory
    mode: "0755"

- name: Copier le certificat CA Nexus pour Docker
  copy:
    src: /etc/nginx/ssl/nexus.crt
    dest: "/etc/docker/certs.d/{{ nexus_registry_url }}/ca.crt"
    remote_src: yes
    mode: "0644"

- name: Login Docker sur Nexus
  shell: |
    echo '{{ nexus_password }}' | docker login {{ nexus_registry_url }} -u {{ nexus_username }} --password-stdin
  register: nexus_login_result
  changed_when: "'Login Succeeded' in nexus_login_result.stdout"

- name: Push de l'image vers Nexus
  command: docker push {{ backend_full_image_name }}
  register: backend_push_result

- name: Afficher le résultat du push
  debug:
    var: backend_push_result.stdout_lines
