---
audit_policy_path: /etc/kubernetes/audit-policy.yaml
audit_log_dir: /var/log/kubernetes/audit
audit_log_path: /var/log/kubernetes/audit/audit.log

kube_apiserver_manifest: /etc/kubernetes/manifests/kube-apiserver.yaml
kube_apiserver_backup: /etc/kubernetes/manifests/kube-apiserver.yaml.bak-audit

audit_log_maxage: 30
audit_log_maxbackup: 10
audit_log_maxsize: 100
