[tools]
localhost ansible_connection=local

[masters]
master1 ansible_host=10.10.0.11

[workers]
worker1 ansible_host=10.10.0.21
worker2 ansible_host=10.10.0.22

[k8s:children]
masters
workers

[all:children]
tools
k8s

[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=/home/vagrant/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
