backend_namespace: project

backend_app_name: backend
backend_container_name: backend

backend_image: "10.10.0.10:8443/backend-students-app:1.0"
backend_image_pull_policy: Always

backend_replicas: 1

backend_container_port: 5000
backend_service_port: 5000
backend_service_type: ClusterIP

backend_db_host: mysql
backend_db_port: "3306"
backend_db_name: appdb
backend_db_user: appuser
backend_db_password: apppass123

backend_configmap_name: backend-config
backend_secret_name: backend-secret
backend_deployment_name: backend
backend_service_name: backend

backend_kubeconfig: /home/vagrant/.kube/config

backend_resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
