- name: Générer l'Ingress frontend
  template:
    src: frontend-ingress.yml.j2
    dest: /tmp/frontend-ingress.yml
    mode: "0644"

- name: Générer l'Ingress backend
  template:
    src: backend-ingress.yml.j2
    dest: /tmp/backend-ingress.yml
    mode: "0644"

- name: Appliquer l'Ingress frontend
  command: kubectl apply -f /tmp/frontend-ingress.yml
  environment:
    KUBECONFIG: "{{ app_ingress_kubeconfig }}"

- name: Appliquer l'Ingress backend
  command: kubectl apply -f /tmp/backend-ingress.yml
  environment:
    KUBECONFIG: "{{ app_ingress_kubeconfig }}"
