---
- name: App Ingress | Générer le manifeste frontend ingress
  become: true
  template:
    src: frontend-ingress.yml.j2
    dest: /tmp/frontend-ingress.yml

- name: App Ingress | Générer le manifeste backend ingress
  become: true
  template:
    src: backend-ingress.yml.j2
    dest: /tmp/backend-ingress.yml

- name: App Ingress | Appliquer le frontend ingress
  become: true
  command: kubectl apply -f /tmp/frontend-ingress.yml
  environment:
    KUBECONFIG: "{{ app_ingress_kubeconfig }}"

- name: App Ingress | Appliquer le backend ingress
  become: true
  command: kubectl apply -f /tmp/backend-ingress.yml
  environment:
    KUBECONFIG: "{{ app_ingress_kubeconfig }}"
