---
- name: App Ingress | Vérifier les ingress
  become: true
  command: kubectl get ingress -n {{ app_ingress_namespace }}
  environment:
    KUBECONFIG: "{{ app_ingress_kubeconfig }}"
  register: app_ingress_result
  changed_when: false

- name: App Ingress | Afficher les ingress
  debug:
    var: app_ingress_result.stdout_lines

- name: App Ingress | Vérifier les détails des ingress
  become: true
  command: kubectl describe ingress -n {{ app_ingress_namespace }}
  environment:
    KUBECONFIG: "{{ app_ingress_kubeconfig }}"
  register: app_ingress_describe
  changed_when: false

- name: App Ingress | Afficher les détails
  debug:
    var: app_ingress_describe.stdout_lines
