- name: Ajouter l'utilisateur Jenkins au groupe docker
  user:
    name: "{{ jenkins_user }}"
    groups: docker
    append: yes

- name: Créer le dossier Docker de Jenkins
  file:
    path: /var/lib/jenkins/.docker
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0700"

- name: Créer le dossier des certificats Docker pour Jenkins
  file:
    path: "{{ jenkins_docker_certs_dir }}"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0755"

- name: Copier le certificat Nexus pour Docker côté Jenkins
  copy:
    src: "{{ nexus_ca_src }}"
    dest: "{{ jenkins_docker_certs_dir }}/ca.crt"
    remote_src: yes
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0644"

- name: Redémarrer Jenkins après configuration Docker
  systemd:
    name: jenkins
    state: restarted
