- name: Vérifier si kubectl est déjà installé
  stat:
    path: "{{ kubectl_binary_path }}"
  register: kubectl_binary_stat

- name: Installer les paquets requis pour le dépôt Kubernetes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present
    update_cache: yes
  when: not kubectl_binary_stat.stat.exists

- name: Créer le dossier des keyrings APT
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  when: not kubectl_binary_stat.stat.exists

- name: Télécharger la clé APT Kubernetes
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o {{ kubernetes_apt_keyring }}
  args:
    creates: "{{ kubernetes_apt_keyring }}"
  when: not kubectl_binary_stat.stat.exists

- name: Ajouter le dépôt APT Kubernetes
  copy:
    dest: "{{ kubernetes_apt_repo_file }}"
    content: "{{ kubernetes_apt_repo }}\n"
    mode: "0644"
  when: not kubectl_binary_stat.stat.exists

- name: Mettre à jour le cache APT Kubernetes
  apt:
    update_cache: yes
  when: not kubectl_binary_stat.stat.exists

- name: Installer kubectl sur tools
  apt:
    name: kubectl
    state: present
  when: not kubectl_binary_stat.stat.exists
