- name: Jenkins Setup | Plugins
  import_tasks: install_plugins.yml

- name: Jenkins Setup | Docker
  import_tasks: docker.yml

- name: Jenkins Setup | Kubectl
  import_tasks: kubectl.yml

- name: Jenkins Setup | Kubernetes
  import_tasks: kubeconfig.yml
