---
cosign_version: "v2.6.1"
cosign_arch: "amd64"
cosign_install_path: "/usr/local/bin/cosign"

cosign_key_dir: "/home/vagrant/cosign"
cosign_private_key_path: "/home/vagrant/cosign/cosign.key"
cosign_public_key_path: "/home/vagrant/cosign/cosign.pub"

cosign_owner: "vagrant"
cosign_group: "vagrant"
