---
- name: Preparation generale
  hosts: all
  become: true
  roles:
    - common
    - nfs

- name: Installer Trivy sur tools
  hosts: tools
  become: true
  roles:
    - role: trivy
      tags: trivy

- name: Preparation Kubernetes
  hosts: k8s
  become: true
  roles:
    - container_runtime
    - kubernetes

- name: Initialiser le master
  hosts: masters
  become: true
  roles:
    - master
    - flannel

- name: Faire rejoindre les workers
  hosts: workers
  become: true
  roles:
    - workers

- name: Ajouter les labels
  hosts: masters
  become: true
  roles:
    - labels

- name: Configure Kubernetes RBAC security
  hosts: masters
  become: true
  roles:
    - role: security_rbac
      tags: security_rbac

- name: Installer ingress
  hosts: masters
  become: true
  roles:
    - ingress

- name: Create application Kubernetes Secrets
  hosts: masters
  become: true
  roles:
    - role: app_secrets
      tags: app_secrets

- name: Creer le stockage
  hosts: masters
  become: true
  roles:
    - storage

- name: Deployer MySQL
  hosts: masters
  become: true
  roles:
    - mysql

- name: Preparation tools
  hosts: tools
  become: true
  roles:
    - tools_prepare
    - nfs

- name: Installer Nexus
  hosts: tools
  become: true
  roles:
    - nexus

- name: Activer TLS pour Nexus
  hosts: tools
  become: true
  roles:
    - nexus_proxy_tls

- name: Construire et pousser l'image backend
  hosts: tools
  become: true
  roles:
    - backend_image

- name: Faire confiance au registre Nexus sur le cluster
  hosts: k8s
  become: true
  roles:
    - registry_tls_trust

- name: Deployer le backend
  hosts: masters
  become: true
  roles:
    - backend

- name: Construire et pousser l'image frontend
  hosts: tools
  become: true
  roles:
    - frontend_image

- name: Deployer le frontend
  hosts: masters
  become: true
  roles:
    - frontend

- name: Deployer l'Ingress applicatif
  hosts: masters
  become: true
  roles:
    - app_ingress
# ============================================================
# 19. Installer Gitea sur tools
#    Gitea : http://10.10.0.10:3000
#    Admin : salhi
# ============================================================
- name: Installer Gitea
  hosts: tools
  become: true
  roles:
    - gitea

- name: Deployer Jenkins dans Kubernetes
  hosts: masters
  become: true
  roles:
    - jenkins

- name: Prepare Helm client on tools
  hosts: tools
  become: true
  roles:
    - role: helm_client
      tags: helm_client

- name: Installer Prometheus dans Kubernetes
  hosts: tools
  become: true
  roles:
    - role: prometheus
      tags: prometheus

- name: Installer Grafana dans Kubernetes
  hosts: tools
  become: true
  roles:
    - role: grafana
      tags: grafana

- name: Configure Gitea webhooks for Jenkins pipelines
  hosts: tools
  become: false
  roles:
    - role: gitea_webhook
  tags: gitea_webhook
